name: Run system tests

on:
  push:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.test --tag dask-lightgbm:${GITHUB_SHA}
        docker-compose up --abort-on-container-exit
